### ISSUE TITLE
Fix monitorandoView

### ISSUE THREAD

**Issue by rinaldosbj** [rinaldosbj/IGuard#15]
quando coloca para simular o layout todo quebra

**Comment by miggelucas** [comment]
Isso tem acontecido independente da versão do Apple Watch? Tu tem alguma suspeita do que poderia tar causando isso? 

De qualquer forma, essa tela vai precisar ser toda refatorada com base na nova verão do figma. No entanto, era bom a gente tentar entender o que foi que houve para ficar ligado e evitar que tenhamos problemas com autoLayout novamente.

**Comment by rinaldosbj** [comment]
perfeito, acontece sim com outros devices, mas *acho* que este problema também estava ligado aquele glich dos navigationsViews um dentro do outro

**Comment by rinaldosbj** [comment]
começando a trabalhar nisso na branch feature/Monitoring

**Comment by rinaldosbj** [comment]
era isso mesmo, corrigido
